### PR TITLE
BalanceBoard weight interpolation

### PR DESCRIPTION
**Pull request by greso**
This pull requests adds reading calibration data from the balance board and interpolating the weight data with it.

Feel free to merge it or to use it as a reference when implementing it yourself.

https://github.com/takeru/Wiimote/issues/2

Cheers

### CODE REVIEW

**Comment by EpicLPer** [comment]
Are you working on a functioning Smart Scale with this pull request? Cause that's what I also wanted to try and work on, despite never having written a line of code for an ESP before heh :P Would've been my first project then to get started.

**Comment by EpicLPer** [comment]
Tried compiling this on an ESP32 from AzDelivery but sadly got an error... Any ideas why? Not really familiar with the whole Arduino IDE.

https://pastebin.com/wY7yXmxp

**Comment by greso** [comment]
There was an error in my commit so I updated the pull request.

@EpicLPer I don't have any plans to create a smart scale. 
The errors you are getting seem to come from a wrong include (multiple definition of...). Just include the Wiimote.h file.
I am using PlatformIO and not the Arduino IDE.

**Comment by EpicLPer** [comment]
Hm, not a programmer so not sure :) Not even sure how to use PlatformIO.

EDIT: Got the Example code to compile via Arduino IDE now! Works fine for my board :) A reconnect-code would be nice too if possible somehow, this would enable to make a Smart Scale out of this device! :D

**Comment by takeru** [comment]
@greso Nice hack!! Thank you!
I did not try this work, but I read changes. I think it may work well, maybe.
Please try it, anyone??

**Comment by wraybowling** [comment]
I've been making use of this for about a month now and it's working well. Nice job.

**Pull request merged**
